[env:esp32c6]
platform = https://github.com/pioarduino/platform-espressif32.git#54.03.20
board = esp32-c6-devkitc-1
framework = arduino

; >>> belangrijk: forceer flash size naar 4MB <<<
board_build.flash_size = 4MB
board_upload.flash_size = 4MB

; (optioneel, maar vaak nodig als je partitions niet matchen)
; board_build.partitions = default.csv
; of een 4MB-partition csv als je die gebruikt

monitor_speed = 115200
upload_speed = 921600

build_flags =
  -D ARDUINO_USB_MODE=1
  -D ARDUINO_USB_CDC_ON_BOOT=1

lib_deps =
  adafruit/Adafruit GFX Library
  adafruit/Adafruit ST7735 and ST7789 Library
  waspinator/AccelStepper
  knolleary/PubSubClient
  bblanchon/ArduinoJson
  https://github.com/tzapu/WiFiManager.git
  https://github.com/pstolarz/OneWireNg.git
  DNSServer
